schedules:
  - cron: "50 15 * * *"
    displayName: Daily 23:50 UTC
    branches:
      include:
        - main

jobs:
- job: UpdateWAFPolicy
  displayName: Update Azure Front Door WAF Policy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Install Azure CLI'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azurerm'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az network front-door waf-policy rule match-condition add --match-variable RemoteAddr --operator IPMatch --values 1.1.1.1 2.2.2.2 3.3.3.3 --name Blacklist --policy-name WAFPOC --resource-group Eugene-POC --negate false
        az network front-door waf-policy rule match-condition remove --index 0 --name Blacklist --policy-name WAFPOC --resource-group Eugene-POC