schedules:
  - cron: "50 15 * * *"
    displayName: Daily 23:50 UTC
    branches:
      include:
        - main

jobs:
- job: UpdateWAFPolicy
  displayName: Update Azure Front Door WAF Policy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Install Azure CLI'
  - script: |
      IP_LIST=$(cat blacklist_IP.txt | tr '\n' ' ')
      az network front-door waf-policy rule match-condition add --match-variable RemoteAddr --operator IPMatch --values $IP_LIST --name Blacklist --policy-name WAFPOC --resource-group Eugene-POC --negate false
    displayName: 'Update WAF Policy with IPs from blacklist_IP.txt'
    env:
      GITHUB_REPOSITORY: 'eugenewang-gd/fd-waf-poc'
      GITHUB_TOKEN: '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'
  - script: |
      az network front-door waf-policy rule match-condition remove --index 0 --name Blacklist --policy-name WAFPOC --resource-group Eugene-POC
    displayName: 'Remove WAF Policy Match Condition'
