trigger:
  branches:
    include:
      - main
  paths:
    include:
      - blacklist_IP.txt

jobs:
- job: UpdateWAFPolicy
  displayName: Update Azure Front Door WAF Policy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Install Azure CLI'
  - script: |
      az config set extension.use_dynamic_install=yes_without_prompt
    displayName: 'Enable Dynamic Install for Preview Extensions'
  - script: |
      az login --service-principal --username 93d25583-8b50-4c43-bec1-5e24e730c758 --password Vl58Q~eCq4.gTvlMjG3iA8CvnBmrbWdPD4u7cdh6 --tenant 7f6bcd3a-7ec3-4e56-b0aa-c1b641c97749
    displayName: 'Login to Azure CLI'
  - script: |
      IP_LIST=$(cat blacklist_IP.txt | tr '\n' ' ')
      az network front-door waf-policy rule match-condition add --match-variable RemoteAddr --operator IPMatch --values $IP_LIST --name Blacklist --policy-name WAFPOC --resource-group Eugene-POC --negate false
    displayName: 'Update WAF Policy with IPs from blacklist_IP.txt'
    env:
      GITHUB_REPOSITORY: 'eugenewang-gd/fd-waf-poc'
      GITHUB_TOKEN: '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'
  - script: |
      az network front-door waf-policy rule match-condition remove --index 0 --name Blacklist --policy-name WAFPOC --resource-group Eugene-POC
    displayName: 'Remove WAF Policy Match Condition'
